//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConfWebAccess.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class confabstract
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public confabstract()
        {
            this.presenters = new HashSet<presenter>();
        }
    
        public int id { get; set; }
        public string userid { get; set; }
        public string title { get; set; }
        public string summary { get; set; }
        public string objective1 { get; set; }
        public string objective2 { get; set; }
        public string objective3 { get; set; }
        public string category { get; set; }
        public string submitdate { get; set; }
        public Nullable<System.DateTime> createdate { get; set; }
        public string status { get; set; }
        public bool submitted { get; set; }
    
        public virtual AspNetUser AspNetUser { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<presenter> presenters { get; set; }
    }
}
