//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConfWebAccess.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DB_A0B2A3_conferenceEntities : DbContext
    {
        public DB_A0B2A3_conferenceEntities()
            : base("name=DB_A0B2A3_conferenceEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AspNetRole> AspNetRoles { get; set; }
        public virtual DbSet<AspNetUserClaim> AspNetUserClaims { get; set; }
        public virtual DbSet<AspNetUserLogin> AspNetUserLogins { get; set; }
        public virtual DbSet<SysUserType> SysUserTypes { get; set; }
        public virtual DbSet<categorylist> categorylists { get; set; }
        public virtual DbSet<presenter> presenters { get; set; }
        public virtual DbSet<confabstract> confabstracts { get; set; }
        public virtual DbSet<SysSetting> SysSettings { get; set; }
        public virtual DbSet<SysFilePath> SysFilePaths { get; set; }
        public virtual DbSet<AspNetUser> AspNetUsers { get; set; }
        public virtual DbSet<lecture> lectures { get; set; }
        public virtual DbSet<studentclass> studentclasses { get; set; }
        public virtual DbSet<survey> surveys { get; set; }
    }
}
