//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConfWebAccess.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class presenter
    {
        public int id { get; set; }
        public Nullable<int> abstractid { get; set; }
        public string fullname { get; set; }
        public string organization { get; set; }
        public string bio { get; set; }
    
        public virtual confabstract confabstract { get; set; }
    }
}
