//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConfWebAccess.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class studentclass
    {
        public int id { get; set; }
        public string studentid { get; set; }
        public int classid { get; set; }
        public Nullable<System.DateTime> scandate { get; set; }
    
        public virtual lecture lecture { get; set; }
        public virtual AspNetUser AspNetUser { get; set; }
        public virtual lecture1 lecture1 { get; set; }
    }
}
