//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConfWebAccess.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class survey
    {
        public int id { get; set; }
        public string userid { get; set; }
        public int lectureid { get; set; }
        public int Q1 { get; set; }
        public int Q2 { get; set; }
        public int Q3 { get; set; }
        public int Q4 { get; set; }
        public int Q5 { get; set; }
        public int Q6 { get; set; }
        public int Q7 { get; set; }
        public int Q8 { get; set; }
        public string Q9 { get; set; }
    
        public virtual AspNetUser AspNetUser { get; set; }
        public virtual lecture lecture { get; set; }
    }
}
